### ISSUE TITLE
Clean up Discrepancies with Kul

### ISSUE THREAD

**Issue by Rackiera** [Rackiera/threa#2]
Azkul:
-Remove mentions of large fins / wings. Update overall biology and anatomy.

Hozkul:
- Update anatomy, add wings made for climbing
- Hozkul lick iron ore to acquire iron for their scales and especially their plates.

Trezkul: 
- Adjust fang orientation not to be retractable.
- Migrate in winter towards the southern half of the temperate zone where it is warmer
- Have plates along back, not ridges

Izkul
- Remove mention of vestigial wings

**Comment by DraaGulFireclaw** [comment]
No longer relevant? We will likely rework the kul a lot as we do the Threa Rework anyway.

A new, improved issue should be created when this comes up again.
